### ISSUE TITLE
原本那个不加多音字表 没办法返回多个拼音么

### ISSUE THREAD

**Issue by joker-fu** [pansong291/SimplePinyin#1]

**Comment by pansong291** [comment]
嗯，原本那个是根据词组返回拼音的，比如 `重量` 返回的是 `ZHONGLIANG`，`重庆` 返回的是 `CHONGQING`。而一个 `重` 字只返回 `CHONG`。

**Comment by joker-fu** [comment]
实在没闹明白算法 我的意思 一个字重 能不能返回它所有的拼音 不加多音字表的情况下

**Comment by joker-fu** [comment]
还有 哦和哈等多音都不对样 哦 正确的应该是E/O 多音查出来是 E/O/WO 哈 正确的应该是HA 多音查出来是HA/KA 类似的好像还有很多

**Comment by pansong291** [comment]
> 实在没闹明白算法 我的意思 一个字重 能不能返回它所有的拼音 不加多音字表的情况下

算法你可以参考[打造最好的Java拼音库TinyPinyin（一）：单字符转拼音的极致优化](http://promeg.io/2017/03/18/tinypinyin-part-1/#2-单字符转拼音的极致优化)，因为原本TinyPinyin就没有做单字的多音，所以不加多音表没办法返回多个拼音，只能返回其中一个。换句话说，每个字都成了单音字，没有多音字的存在。因为我是在TinyPinyin的基础上改的，所以我加了一个多音表，如果全部重新写的话，就稍微麻烦一点。

**Comment by pansong291** [comment]
> 还有 哦和哈等多音都不对样 哦 正确的应该是E/O 多音查出来是 E/O/WO 哈 正确的应该是HA 多音查出来是HA/KA 类似的好像还有很多

关于这个问题，汉字转拼音的数据库最终来源是[pinyin4j](http://pinyin4j.sourceforge.net/)项目，`哦` 字的Unicode码是 `54E6`，在pinyin4j源代码里有一个[unicode_to_hanyu_pinyin.txt](https://sourceforge.net/p/pinyin4j/code/HEAD/tree/data/trunk/unicode_to_hanyu_pinyin.txt)文件，里面有一行内容是 `54E6 (e2,o2,o4,wo2,wo4)`，数字表示声调，不看声调的话，pinyin4j里面的 `哦` 字的确是有 `e`，`o`，`wo` 这三个拼音，如果确实拼音有错误，那应该是pinyin4j的错误。

**Comment by joker-fu** [comment]
好的 谢谢
